# Databricks App configuration
# This file is intentionally minimal; the bundle deployment references ./app as source code.
command: [
  "python",
  "app.py"
]

env:
  - name: JOB_ID
    valueFrom: "app-job"

# env:
#   - name: UV_INDEX_URL
#     value: "https://pypi-proxy.cloud.databricks.com/simple"
#   - name: PIP_INDEX_URL
#     value: "https://pypi-proxy.cloud.databricks.com/simple"


